server {
    listen 80;
    server_name adma.co.in www.adma.co.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name ijdm.adma.co.in www.ijdm.adma.co.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name adma.co.in www.adma.co.in;

    ssl_certificate /etc/letsencrypt/live/adma.co.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adma.co.in/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /cms/ {
        proxy_pass http://cms:1337/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl http2;
    server_name ijdm.adma.co.in www.ijdm.adma.co.in;

    ssl_certificate /etc/letsencrypt/live/adma.co.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adma.co.in/privkey.pem;

    location / {
        proxy_pass http://ojs:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}