CREATE TABLE membership_forms (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  email VARCHAR(255),
  current_step INT DEFAULT 1,
  status ENUM('DRAFT','SUBMITTED','APPROVED','REJECTED','PENDING') DEFAULT 'DRAFT',
  data JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);