export const FORM_STATUS = {
    DRAFT: "DRAFT",
    FORWARDED_TO_TREASURER: "FORWARDED_TO_TREASURER",
    TREASURER_REJECTED: "TREASURER_REJECTED",
    FORWARDED_TO_SECRETARY: "FORWARDED_TO_SECRETARY",
    SECRETARY_REJECTED: "SECRETARY_REJECTED",
    APPROVED: "APPROVED"
  };
  
export const EDITABLE_STATES = [
FORM_STATUS.DRAFT,
FORM_STATUS.TREASURER_REJECTED,
FORM_STATUS.SECRETARY_REJECTED
];
  